export const GET_ATTENDENCE_RECORD_REQUEST = " GET_ATTENDENCE_RECORD_REQUEST";
export const GET_ATTENDENCE_RECORD_SUCCESS = " GET_ATTENDENCE_RECORD_SUCCESS";
export const GET_ATTENDENCE_RECORD_ERROR = " GET_ATTENDENCE_RECORD_ERROR";



export const ADD_ATTENDENCE_RECORD_REQUEST = " ADD_ATTENDENCE_RECORD_REQUEST";
export const ADD_ATTENDENCE_RECORD_SUCCESS = " ADD_ATTENDENCE_RECORD_SUCCESS";
export const ADD_ATTENDENCE_RECORD_ERROR = " ADD_ATTENDENCE_RECORD_ERROR";

export const UPDATE_ATTENDENCE_RECORD_REQUEST="UPDATE_ATTENDENCE_RECORD_REQUEST";
export const UPDATE_ATTENDENCE_RECORD_SUCCESS="UPDATE_ATTENDENCE_RECORD_SUCCESS";
export const UPDATE_ATTENDENCE_RECORD_ERROR="UPDATE_ATTENDENCE_RECORD_ERROR";

